# -*- coding: utf-8 -*-
"""combined_tfidf_sbert_binary.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12B54V_3iq_BxSu63AE6DPKOACHLQuohV
"""

import json
import numpy as np

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, accuracy_score

from sentence_transformers import SentenceTransformer

def load_jsonl(path):
    data = []
    with open(path, "r", encoding="utf-8") as f:
        for line in f:
            if line.strip():
                data.append(json.loads(line))
    return data

train_data = load_jsonl(r"C:\Users\Lenovo\Desktop\semEval assests\synthetic_data_for_classification (4).jsonl")
print("Train samples:", len(train_data))

def clean_text_list(texts):
    return [t if isinstance(t, str) else "" for t in texts]

#extract train text and binary labels
train_anchor = clean_text_list([d["anchor_text"] for d in train_data])
train_a = clean_text_list([d["text_a"] for d in train_data])
train_b = clean_text_list([d["text_b"] for d in train_data])

y_train = [1 if d["text_a_is_closer"] == 1 else 0 for d in train_data]

sum(x is None for x in train_anchor), \
sum(x is None for x in train_a), \
sum(x is None for x in train_b)

#tf-idf features
tfidf = TfidfVectorizer(
    max_features=8000,
    ngram_range=(1, 2),
    stop_words="english"
)

tfidf_anchor = tfidf.fit_transform(train_anchor)
tfidf_a = tfidf.transform(train_a)
tfidf_b = tfidf.transform(train_b)

#tf-idf binary features
X_tfidf_train = np.hstack([
    np.abs(tfidf_anchor - tfidf_a).toarray(),
    np.abs(tfidf_anchor - tfidf_b).toarray()
])

print("TF-IDF train shape:", X_tfidf_train.shape)

#sbert features

#load data
sbert = SentenceTransformer("all-MiniLM-L6-v2")

#encode train text
anchor_emb = sbert.encode(train_anchor, batch_size=32, show_progress_bar=True)
a_emb = sbert.encode(train_a, batch_size=32, show_progress_bar=True)
b_emb = sbert.encode(train_b, batch_size=32, show_progress_bar=True)


#sbert binary feature


X_sbert_train = np.hstack([
    np.abs(anchor_emb - a_emb),
    np.abs(anchor_emb - b_emb)
])

print("SBERT train shape:", X_sbert_train.shape)

#concatening both

X_train = np.hstack([
    X_tfidf_train,   # lexical features
    X_sbert_train    # semantic features
])

# columns = TF-IDF features + SBERT features
print("Combined train shape:", X_train.shape)

"""X_tfidf_train:

 Word / n-gram based features capturing lexical overlap between texts
 (surface-level similarity using TF-IDF)

 X_sbert_train:

 Semantic distance-based features from SBERT embeddings
 (captures meaning-level similarity independent of exact words)


 np.hstack:

 Horizontally concatenate TF-IDF and SBERT features
 so each sample has both lexical and semantic information



Combined feature matrix:
 rows = samples
 columns = TF-IDF features + SBERT features

"""

#trsin classifier
clf=LogisticRegression(max_iter=1000)
clf.fit(X_train,y_train)
print("combined model trained")

#testing on dev data

dev_data = load_jsonl(r"C:\Users\Lenovo\Desktop\semEval assests\dev_track_a.jsonl")
print("Dev samples:", len(dev_data))

#extract dev texts
dev_anchor = [d["anchor_text"] for d in dev_data]
dev_a = [d["text_a"] for d in dev_data]
dev_b = [d["text_b"] for d in dev_data]

y_dev = [1 if d["text_a_is_closer"] == 1 else 0 for d in dev_data]

#tf idf dev feaatures
tfidf_anchor_dev = tfidf.transform(dev_anchor)
tfidf_a_dev = tfidf.transform(dev_a)
tfidf_b_dev = tfidf.transform(dev_b)

X_tfidf_dev = np.hstack([
    np.abs(tfidf_anchor_dev - tfidf_a_dev).toarray(),
    np.abs(tfidf_anchor_dev - tfidf_b_dev).toarray()
])

#sbert dev features
anchor_emb_dev = sbert.encode(dev_anchor, batch_size=32, show_progress_bar=True)
a_emb_dev = sbert.encode(dev_a, batch_size=32, show_progress_bar=True)
b_emb_dev = sbert.encode(dev_b, batch_size=32, show_progress_bar=True)

X_sbert_dev = np.hstack([
    np.abs(anchor_emb_dev - a_emb_dev),
    np.abs(anchor_emb_dev - b_emb_dev)
])

#combine dev features
X_dev = np.hstack([
    X_tfidf_dev,
    X_sbert_dev
])

print("Combined dev shape:", X_dev.shape)

#predicting final metrics
y_pred = clf.predict(X_dev)

print("Accuracy:", accuracy_score(y_dev, y_pred))
print(classification_report(y_dev, y_pred))