# -*- coding: utf-8 -*-
"""sentence-similarity-using-sentence-transformers.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AyckHOjF30lC9vOQCt0n6CEDDLD-wMZo
"""

from sentence_transformers import SentenceTransformer

# Fastest Sentence Transformer model
model = SentenceTransformer('all-MiniLM-L6-v2')

anchor_sentence = ["The film takes place in Burma and India during World War II.\nA British officer falls in love with his Japanese instructor at a military language school. They start a romance, but she is regarded as the enemy and is not accepted by his countrymen. They marry in secret and plan on spending his two weeks' leave together. When one of the other officers is injured, he is sent into the field as an interrogator. Later he is captured by the Japanese army when he is patrolling with a brigadier and an Indian driver in a Japanese-controlled zone. He escapes and returns to his own lines, only to discover that his wife is suffering from a brain tumour. Although the doctor initially gives her good odds of surviving, she dies after an operation."]
test_sentences = ["During the Irish War of Independence in 1921, Irish rebel leader Dennis Riordan (Aherne) and English aristocrat Helen Drummond (Oberon) meet and fall in love. Riordan is pursued, however, by British army officer Captain Preston (Niven).\nThe original film ended with Riordan getting shot and killed, but did not do well at the box office. A happier ending was also filmed which has Riordan being shot but surviving; all subsequent versions have. The original cut has since been lost.\nThe movie has several comic relief scenes: after a raid on an IRA \"safe house\", British officers grumble about being not being able to find Riordan, who is in fact standing just behind them; when the Irish Delegation goes to a formal ball and is asked by the footman for their names to be announced, the delegation replies in Irish.", "1914, German advance through Belgium: the young war volunteer Alexander 'Alex' Haller (Schell) is given water by an equally young Belgian woman (Berger). \n1917, Third Battle of Flanders: Alex, now a 2nd lieutenant, is tired about the propaganda at the Home Front, so he spends his furlough in the hinterland of the Western Front. \nWhile boarding in a brothel, he meets the young woman again. They fall in love. \nLate 1918, German retreat after the Armistice: Engele and Alex meet again only to be harassed by a Belgian mob. Shortly prior to be hanged by the mob, a group of passing Belgian soldiers, tired about killing, saves them. End of the tale."]

anchor_embeddings = model.encode(anchor_sentence)

test_embeddings = model.encode(test_sentences)

similarity_scores = model.similarity(anchor_embeddings, test_embeddings)

import torch

if torch.argmax(similarity_scores) == 0:
  print("Text a is closer")
else:
  print("Text b is closer")

