# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OyrxMLCvlB_Z60r9L0wmLmEHrKOkn0MV
"""

!pip install -q transformers accelerate sentencepiece scikit-learn

import torch
import torch.nn as nn
import pandas as pd
import numpy as np
import random

from torch.utils.data import Dataset, DataLoader
from transformers import (
    DebertaV2Tokenizer,
    DebertaV2Model,
    get_cosine_schedule_with_warmup
)

from torch.cuda.amp import autocast, GradScaler
from sklearn.model_selection import KFold
import json

SEED = 42
random.seed(SEED)
np.random.seed(SEED)
torch.manual_seed(SEED)
torch.cuda.manual_seed_all(SEED)

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(device)

train_df = pd.read_json(
    "/content/synthetic_data_for_classification (4).jsonl",
    lines=True
)

train_df.head()

MODEL_NAME = "microsoft/deberta-v3-base"
MAX_LEN = 192

tokenizer = DebertaV2Tokenizer.from_pretrained(MODEL_NAME)

class SemEvalDataset(Dataset):
    def __init__(self, df, training=True):
        self.df = df.reset_index(drop=True)
        self.training = training

    def __len__(self):
        return len(self.df)

    def __getitem__(self, idx):
        row = self.df.iloc[idx]

        anchor = str(row["anchor_text"])
        text_a = str(row["text_a"])
        text_b = str(row["text_b"])

        label = 1 if row["text_a_is_closer"] else 0

        if self.training and random.random() < 0.5:
            text_a, text_b = text_b, text_a
            label = 1 - label

        def tok(x):
            return tokenizer(
                x,
                truncation=True,
                padding="max_length",
                max_length=MAX_LEN,
                return_tensors="pt"
            )

        anc = tok(anchor)
        a = tok(text_a)
        b = tok(text_b)

        return {
            "anc_ids": anc["input_ids"].squeeze(0),
            "anc_mask": anc["attention_mask"].squeeze(0),
            "a_ids": a["input_ids"].squeeze(0),
            "a_mask": a["attention_mask"].squeeze(0),
            "b_ids": b["input_ids"].squeeze(0),
            "b_mask": b["attention_mask"].squeeze(0),
            "label": torch.tensor(label, dtype=torch.long)
        }

#model defination
class MeanPooling(nn.Module):
    def forward(self, token_embeddings, mask):
        mask = mask.unsqueeze(-1).expand(token_embeddings.size())
        summed = (token_embeddings * mask).sum(1)
        counts = mask.sum(1).clamp(min=1e-9)
        return summed / counts

class DebertaRanker(nn.Module):
    def __init__(self):
        super().__init__()
        self.encoder = DebertaV2Model.from_pretrained(MODEL_NAME)
        self.pool = MeanPooling()

        # Freeze first 4 layers
        for name, param in self.encoder.named_parameters():
            if any(f"layer.{i}." in name for i in range(4)):
                param.requires_grad = False

    def encode(self, ids, mask):
        out = self.encoder(input_ids=ids, attention_mask=mask)
        return self.pool(out.last_hidden_state, mask)

    def forward(self, anc_ids, anc_mask, txt_ids, txt_mask):
        anc = self.encode(anc_ids, anc_mask)
        txt = self.encode(txt_ids, txt_mask)
        return nn.functional.cosine_similarity(anc, txt)

def contrastive_loss(anchor, pos, neg, temp=0.07):
    pos_sim = torch.exp((anchor * pos).sum(dim=1) / temp)
    neg_sim = torch.exp((anchor * neg).sum(dim=1) / temp)
    return -torch.log(pos_sim / (pos_sim + neg_sim)).mean()

def train_epoch(model, loader, optimizer, scheduler, scaler):
    model.train()
    total_loss = 0

    for batch in loader:
        optimizer.zero_grad(set_to_none=True)

        with autocast():
            anc_emb = model.encode(
                batch["anc_ids"].to(device),
                batch["anc_mask"].to(device)
            )
            pos_emb = model.encode(
                batch["a_ids"].to(device),
                batch["a_mask"].to(device)
            )
            neg_emb = model.encode(
                batch["b_ids"].to(device),
                batch["b_mask"].to(device)
            )

            pos_score = nn.functional.cosine_similarity(anc_emb, pos_emb)
            neg_score = nn.functional.cosine_similarity(anc_emb, neg_emb)

            rank_loss = nn.functional.margin_ranking_loss(
                pos_score, neg_score,
                torch.ones_like(pos_score),
                margin=0.3
            )

            cont_loss = contrastive_loss(anc_emb, pos_emb, neg_emb)

            loss = rank_loss + 0.5 * cont_loss

        scaler.scale(loss).backward()
        scaler.step(optimizer)
        scaler.update()
        scheduler.step()

        total_loss += loss.item()

        # 🔥 FREE MEMORY EVERY STEP
        del anc_emb, pos_emb, neg_emb
        torch.cuda.empty_cache()

    return total_loss / len(loader)

#evaluation
def evaluate(model, loader):
    model.eval()
    correct, total = 0, 0

    with torch.no_grad():
        for batch in loader:
            s1 = model(
                batch["anc_ids"].to(device),
                batch["anc_mask"].to(device),
                batch["a_ids"].to(device),
                batch["a_mask"].to(device)
            )
            s2 = model(
                batch["anc_ids"].to(device),
                batch["anc_mask"].to(device),
                batch["b_ids"].to(device),
                batch["b_mask"].to(device)
            )

            preds = (s1 > s2).long()
            correct += (preds.cpu() == batch["label"]).sum().item()
            total += preds.size(0)

    return correct / total

from sklearn.model_selection import KFold

#k-fold training
kf = KFold(n_splits=5, shuffle=True, random_state=SEED)
model_paths = []

for fold, (tr, va) in enumerate(kf.split(train_df)):
    print(f"\n===== FOLD {fold+1} =====")

    train_ds = SemEvalDataset(train_df.iloc[tr], training=True)
    val_ds = SemEvalDataset(train_df.iloc[va], training=False)

    train_loader = DataLoader(train_ds, batch_size=8, shuffle=True)
    val_loader = DataLoader(val_ds, batch_size=8)

    model = DebertaRanker().to(device)

    optimizer = torch.optim.AdamW(
        filter(lambda p: p.requires_grad, model.parameters()),
        lr=2e-5, weight_decay=0.01
    )

    scheduler = get_cosine_schedule_with_warmup(
        optimizer,
        num_warmup_steps=0,
        num_training_steps=len(train_loader) * 5
    )

    scaler = GradScaler()
    best = 0

    for epoch in range(5):
        loss = train_epoch(model, train_loader, optimizer, scheduler, scaler)
        acc = evaluate(model, val_loader)

        print(f"Epoch {epoch+1} | Loss {loss:.4f} | Val {acc:.4f}")

        if acc > best:
            best = acc
            torch.save(model.state_dict(), f"best_fold_{fold}.pt")

    model_paths.append(f"best_fold_{fold}.pt")
    del model
torch.cuda.empty_cache()

def ensemble_predict(paths, df):
    all_preds = []

    for p in paths:
        model = DebertaRanker().to(device)
        model.load_state_dict(torch.load(p, map_location=device))
        model.eval()

        preds = []

        with torch.no_grad():
            for _, row in df.iterrows():
                def tok(x):
                    return tokenizer(
                        x,
                        truncation=True,
                        padding="max_length",
                        max_length=MAX_LEN,
                        return_tensors="pt"
                    )

                anc = tok(row["anchor_text"])
                a = tok(row["text_a"])
                b = tok(row["text_b"])

                s1 = model(
                    anc["input_ids"].to(device),
                    anc["attention_mask"].to(device),
                    a["input_ids"].to(device),
                    a["attention_mask"].to(device)
                )
                s2 = model(
                    anc["input_ids"].to(device),
                    anc["attention_mask"].to(device),
                    b["input_ids"].to(device),
                    b["attention_mask"].to(device)
                )

                preds.append(1 if s1 > s2 else 0)

        all_preds.append(preds)

    return (np.mean(all_preds, axis=0) > 0.5).astype(int)

dev_df = pd.read_json("/content/dev_track_a.jsonl", lines=True)

preds = ensemble_predict(model_paths, dev_df)
true = dev_df["text_a_is_closer"].astype(int).values

acc = (preds == true).mean()
print("FINAL DEV ENSEMBLE ACCURACY:", acc)