# -*- coding: utf-8 -*-
"""Approach2(SBERT).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ktfiRmAKmA7fwPyJwVqPybQGo5YG7Xw0
"""

import json
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

from sklearn.linear_model import LogisticRegression
from sklearn.svm import LinearSVC
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.metrics.pairwise import cosine_similarity
from sentence_transformers import SentenceTransformer

# 1. LOAD DATA
def load_jsonl(path):
    data = []
    with open(path, "r") as f:
        for line in f:
            data.append(json.loads(line))
    return data

dev_data = load_jsonl("/content/dev_track_a.jsonl")

# 2. PREPARE LISTS
anchors = []
options_a = []
options_b = []
labels = []

for sample in dev_data:
    anchors.append(sample["anchor_text"])
    options_a.append(sample["text_a"])
    options_b.append(sample["text_b"])

    if sample["text_a_is_closer"]:
        labels.append(1)
    else:
        labels.append(2)

print(f"Loaded {len(labels)} samples.")

# 3. SBERT FEATURE EXTRACTION
model = SentenceTransformer('all-MiniLM-L6-v2')

print("Encoding Anchors...")
emb_anchor = model.encode(anchors, show_progress_bar=True)

print("Encoding Option A...")
emb_a = model.encode(options_a, show_progress_bar=True)

print("Encoding Option B...")
emb_b = model.encode(options_b, show_progress_bar=True)

# 4. FEATURE ENGINEERING
sim_a = np.diag(cosine_similarity(emb_anchor, emb_a))
sim_b = np.diag(cosine_similarity(emb_anchor, emb_b))

diff = sim_a - sim_b
X_sbert = np.vstack((sim_a, sim_b, diff)).T

print(f"Feature Matrix Shape: {X_sbert.shape}")

# 5. CLASSIFIERS

# --- Logistic Regression ---
print("\n--- Logistic Regression ---")
lr = LogisticRegression(max_iter=1000)
lr.fit(X_sbert, labels)
lr_preds = lr.predict(X_sbert)

print("Accuracy:", accuracy_score(labels, lr_preds))
print(confusion_matrix(labels, lr_preds))

# --- Linear SVM ---
print("\n--- SVM ---")
svm = LinearSVC(dual="auto")
svm.fit(X_sbert, labels)
svm_preds = svm.predict(X_sbert)

print("Accuracy:", accuracy_score(labels, svm_preds))
print(confusion_matrix(labels, svm_preds))