# -*- coding: utf-8 -*-
"""Track A. Approach 1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mJF69-epWWUyJfsCw3MnoK3SjedMElxv
"""

import json
import numpy as np
import pandas as pd

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

file_path = "/content/dev_track_a.jsonl"

"""Loading the data."""

data = []

with open(file_path, "r", encoding="utf-8") as f:
    for line in f:
        data.append(json.loads(line))

print("Number of samples:", len(data))

"""inspecting the data."""

data[0]

"""Preprocessing the data."""

def preprocess(text):
    return text.lower().strip()

all_texts = []

for sample in data:
    all_texts.append(preprocess(sample["anchor_text"]))
    all_texts.append(preprocess(sample["text_a"]))
    all_texts.append(preprocess(sample["text_b"]))

print(len(all_texts))

"""Creating and fitting the TF-IDF"""

vectorizer = TfidfVectorizer(
    ngram_range=(1, 2),     # unigrams + bigrams
    max_df=0.9,             # ignore very common terms
    min_df=2,               # ignore very rare terms
    stop_words="english"    # allowed minimal preprocessing
)

tfidf_matrix = vectorizer.fit_transform(all_texts)

print("TF-IDF matrix shape:", tfidf_matrix.shape)

"""Creating similarity function."""

def compute_similarities(sample):
    texts = [
        preprocess(sample["anchor_text"]),
        preprocess(sample["text_a"]),
        preprocess(sample["text_b"])
    ]

    vectors = vectorizer.transform(texts)

    sim_anchor_a = cosine_similarity(vectors[0], vectors[1])[0][0]
    sim_anchor_b = cosine_similarity(vectors[0], vectors[2])[0][0]

    return sim_anchor_a, sim_anchor_b

sim_a, sim_b = compute_similarities(data[0])
print("Similarity(anchor, text_a):", sim_a)
print("Similarity(anchor, text_b):", sim_b)
print("Gold label (text_a_is_closer):", data[0]["text_a_is_closer"])

"""Accuracy Evaluation."""

correct = 0

for sample in data:
    sim_a, sim_b = compute_similarities(sample)

    prediction = sim_a > sim_b   # Boolean

    if prediction == sample["text_a_is_closer"]:
        correct += 1

accuracy = correct / len(data)
accuracy